package com.pojo;
// Generated 11 Jul, 2017 4:21:47 AM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Books generated by hbm2java
 */
public class Books implements java.io.Serializable {

	private Integer booksId;
	private String booksName;
	private String author;
	private int price;
	private Set customerDetailses = new HashSet(0);

	public Books() {
	}

	public Books(int price) {
		this.price = price;
	}

	public Books(String booksName, String author, int price, Set customerDetailses) {
		this.booksName = booksName;
		this.author = author;
		this.price = price;
		this.customerDetailses = customerDetailses;
	}

	public Integer getBooksId() {
		return this.booksId;
	}

	public void setBooksId(Integer booksId) {
		this.booksId = booksId;
	}

	public String getBooksName() {
		return this.booksName;
	}

	public void setBooksName(String booksName) {
		this.booksName = booksName;
	}

	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public int getPrice() {
		return this.price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

	public Set getCustomerDetailses() {
		return this.customerDetailses;
	}

	public void setCustomerDetailses(Set customerDetailses) {
		this.customerDetailses = customerDetailses;
	}

}
