package com.pojo;
// Generated 11 Jul, 2017 4:21:47 AM by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * CustomerDetails generated by hbm2java
 */
public class CustomerDetails implements java.io.Serializable {

	private int orderId;
	private Books books;
	private String customerName;
	private String phone;
	private String address;
	private int quantity;
	private int subtotal;
    private Date orderDate;

	public CustomerDetails() {
	}

	public CustomerDetails(int orderId, int quantity) {
		this.orderId = orderId;
		this.quantity = quantity;
	}

	public CustomerDetails(int orderId, Books books, String customerName, String phone, String address, int quantity, int subtotal,
			Date orderDate) {
		this.orderId = orderId;
		this.books = books;
		this.customerName = customerName;
		this.phone = phone;
		this.address = address;
		this.quantity = quantity;
		this.subtotal = subtotal;
		this.orderDate = orderDate;
	}
	
	public int getSubtotal() {
		return subtotal;
	}

	public void setSubtotal(int subtotal) {
		this.subtotal = subtotal;
	}
	public int getOrderId() {
		return this.orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	public Books getBooks() {
		return this.books;
	}

	public void setBooks(Books books) {
		this.books = books;
	}

	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}
	
	@Override
	public String toString() {
		return "CustomerDetails [orderId=" + orderId + ", books=" + books + ", customerName=" + customerName
				+ ", phone=" + phone + ", address=" + address + ", quantity=" + quantity + ", subtotal=" + subtotal
				+ ", orderDate=" + orderDate + "]";
	}

}
