package com.pojo;
// Generated 12 Jul, 2017 7:43:30 PM by Hibernate Tools 5.2.3.Final

/**
 * Customers generated by hbm2java
 */
public class Customers implements java.io.Serializable {

	private String name;
	private String address;
	private String username;
	private String password;
	private String phonenumber;

	public Customers() {
	}

	public Customers(String name) {
		this.name = name;
	}

	public Customers(String name, String address, String username, String password, String phonenumber) {
		this.name = name;
		this.address = address;
		this.username = username;
		this.password = password;
		this.phonenumber = phonenumber;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getPhonenumber() {
		return this.phonenumber;
	}

	public void setPhonenumber(String phonenumber) {
		this.phonenumber = phonenumber;
	}

	@Override
	public String toString() {
		return "Customers [name=" + name + ", address=" + address + ", username=" + username + ", password=" + password
				+ ", phonenumber=" + phonenumber + "]";
	}
	
	

}
